spring:
  application:
    name: spring-cloud-eureka-client

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8888/eureka}
  instance:
    preferIpAddress: true