spring:
  application:
    name: myCli
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /my-health-check
        healthCheckInterval: 20s
        enabled: true
        instanceId: ${spring.application.name}:${random.value}
server:
  port: 8505