# Make the application available at http://localhost:8081
# These are default settings, but we add them for clarity.
server:
  port: 8081
  contextPath: /

# Configure the Authorization Server and User Info Resource Server details
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:7070/authserver/oauth/token
      userAuthorizationUri: http://localhost:7070/authserver/oauth/authorize
      clientId: second
      clientSecret: passwordforauthserver
    resource:
      userInfoUri: http://localhost:9000/user

person:
  url: http://localhost:9000/person

# Proxies the calls to http://localhost:8081/api/* to our REST service at http://localhost:9000/*
# and automatically includes our OAuth2 token in the request headers
zuul:
  routes:
    resource:
      path: /api/**
      url: http://localhost:9000
    user: 
      path: /user/**
      url: http://localhost:9000/user

# Make sure the OAuth2 token is only relayed when using the internal API,
# do not pass any authentication to the external API
proxy:
  auth:
    routes:
      api: oauth2